benchmark = [
    {
        "dataset": "BMS",
        "init_strategy": "worst_ligand",
        "cost_aware": True,
        "n_runs": 5,
        "n_iter": 15,
        "batch_size": 5,
        "max_batch_cost": 20.0,
        "ntrain": 200,
        "prices": "update_ligand_when_used",
    },    
    {
        "dataset": "BMS",
        "init_strategy": "worst_ligand",
        "cost_aware": True,
        "n_runs": 5,
        "n_iter": 15,
        "batch_size": 5,
        "max_batch_cost": 80.0,
        "ntrain": 200,
        "prices": "update_ligand_when_used",
    },
    {
        "dataset": "BMS",
        "init_strategy": "worst_ligand",
        "cost_aware": True,
        "n_runs": 5,
        "n_iter": 15,
        "batch_size": 5,
        "max_batch_cost": 100.0,
        "ntrain": 200,
        "prices": "update_ligand_when_used",
    },
    {
        "dataset": "BMS",
        "init_strategy": "worst_ligand",
        "cost_aware": True,
        "n_runs": 5,
        "n_iter": 15,
        "batch_size": 5,
        "max_batch_cost": 200.0,
        "ntrain": 200,
        "prices": "update_ligand_when_used",
    },
    {
        "dataset": "BMS",
        "init_strategy": "worst_ligand",
        "cost_aware": True,
        "n_runs": 5,
        "n_iter": 15,
        "batch_size": 5,
        "max_batch_cost": 300.0,
        "ntrain": 200,
        "prices": "update_ligand_when_used",
    },
    {
        "dataset": "BMS",
        "init_strategy": "worst_ligand",
        "cost_aware": True,
        "n_runs": 5,
        "n_iter": 15,
        "batch_size": 5,
        "max_batch_cost": 400.0,
        "ntrain": 200,
        "prices": "update_ligand_when_used",
    },
    {
        "dataset": "BMS",
        "init_strategy": "worst_ligand",
        "cost_aware": True,
        "n_runs": 5,
        "n_iter": 15,
        "batch_size": 5,
        "max_batch_cost": 500.0,
        "ntrain": 200,
        "prices": "update_ligand_when_used",
    },
    {
        "dataset": "BMS",
        "init_strategy": "worst_ligand",
        "cost_aware": True,
        "n_runs": 5,
        "n_iter": 15,
        "batch_size": 5,
        "max_batch_cost": 600.0,
        "ntrain": 200,
        "prices": "update_ligand_when_used",
    },
    {
        "dataset": "BMS",
        "init_strategy": "worst_ligand",
        "cost_aware": True,
        "n_runs": 5,
        "n_iter": 15,
        "batch_size": 5,
        "max_batch_cost": 700.0,
        "ntrain": 200,
        "prices": "update_ligand_when_used",
    },
    {
        "dataset": "BMS",
        "init_strategy": "worst_ligand",
        "cost_aware": False,
        "n_runs": 5,
        "n_iter": 15,
        "batch_size": 5,
        "max_batch_cost": 800.0,
        "ntrain": 200,
        "prices": "update_ligand_when_used",
    },
    {
        "dataset": "BMS",
        "init_strategy": "worst_ligand",
        "cost_aware": False,
        "n_runs": 5,
        "n_iter": 15,
        "batch_size": 5,
        "max_batch_cost": 900.0,
        "ntrain": 200,
        "prices": "update_ligand_when_used",
    },
    {
        "dataset": "BMS",
        "init_strategy": "worst_ligand",
        "cost_aware": False,
        "n_runs": 5,
        "n_iter": 15,
        "batch_size": 5,
        "max_batch_cost": 1000.0,
        "ntrain": 200,
        "prices": "update_ligand_when_used",
    },
    {
        "dataset": "BMS",
        "init_strategy": "worst_ligand",
        "cost_aware": True,
        "n_runs": 5,
        "n_iter": 15,
        "batch_size": 5,
        "max_batch_cost": 1200.0,
        "ntrain": 200,
        "prices": "update_ligand_when_used",
    },
    {
        "dataset": "BMS",
        "init_strategy": "worst_ligand",
        "cost_aware": False,
        "n_runs": 5,
        "n_iter": 15,
        "batch_size": 5,
        "max_batch_cost": 20000.0,
        "ntrain": 200,
        "prices": "update_ligand_when_used",
    },
    {
        "dataset": "ebdo_direct_arylation",
        "init_strategy": "worst_ligand",
        "cost_aware": True,
        "n_runs": 10,
        "n_iter": 20,
        "batch_size": 5,
        "max_batch_cost": 0,
        "ntrain": 200,
        "prices": "update_ligand_when_used",
    },
    {
        "dataset": "ebdo_direct_arylation",
        "init_strategy": "worst_ligand",
        "cost_aware": True,
        "n_runs": 10,
        "n_iter": 20,
        "batch_size": 5,
        "max_batch_cost": 1,
        "ntrain": 200,
        "prices": "update_ligand_when_used",
    },
    {
        "dataset": "ebdo_direct_arylation",
        "init_strategy": "worst_ligand",
        "cost_aware": True,
        "n_runs": 10,
        "n_iter": 20,
        "batch_size": 5,
        "max_batch_cost": 2,
        "ntrain": 200,
        "prices": "update_ligand_when_used",
    },
    {
        "dataset": "ebdo_direct_arylation",
        "init_strategy": "worst_ligand",
        "cost_aware": True,
        "n_runs": 10,
        "n_iter": 20,
        "batch_size": 5,
        "max_batch_cost": 3,
        "ntrain": 200,
        "prices": "update_ligand_when_used",
    },
    {
        "dataset": "ebdo_direct_arylation",
        "init_strategy": "worst_ligand",
        "cost_aware": True,
        "n_runs": 10,
        "n_iter": 20,
        "batch_size": 5,
        "max_batch_cost": 4,
        "ntrain": 200,
        "prices": "update_ligand_when_used",
    },
    {
        "dataset": "ebdo_direct_arylation",
        "init_strategy": "worst_ligand",
        "cost_aware": False,
        "n_runs": 10,
        "n_iter": 20,
        "batch_size": 5,
        "max_batch_cost": 5,
        "ntrain": 200,
        "prices": "update_ligand_when_used",
    },
]
