# Benzamide (g00d), Phenethylamine (good), Aniline (good), Morpholine (meh)
benchmark = [
    {
        "dataset": "baumgartner",
        "init_strategy": "worst_ligand_and_more",
        "cost_aware": False,
        "n_runs": 5,
        "n_iter": 24,
        "batch_size": 5,
        "ntrain": 200,
        "prices": "update_all_when_bought",
        "surrogate": "GP",
        "acq_func": "NEI",
        "label": "Aniline_BAUM_NORMAL_GP_NEI",
        "cost_mod": "minus",
        "nucleophile": "Aniline",
    },
    {
        "dataset": "baumgartner",
        "init_strategy": "worst_ligand_and_more",
        "cost_aware": True,
        "n_runs": 5,
        "n_iter": 24,
        "batch_size": 5,
        "ntrain": 200,
        "prices": "update_all_when_bought",
        "surrogate": "GP",
        "acq_func": "NEI",
        "label": "Aniline_BAUM_COST_GP_NEI",
        "cost_mod": "minus",
        "nucleophile": "Aniline",
    },
    {
        "dataset": "baumgartner",
        "init_strategy": "worst_ligand_and_more",
        "cost_aware": False,
        "n_runs": 5,
        "n_iter": 12,
        "batch_size": 5,
        "ntrain": 200,
        "prices": "update_all_when_bought",
        "surrogate": "GP",
        "acq_func": "NEI",
        "label": "Morpholine_BAUM_NORMAL_GP_NEI",
        "cost_mod": "minus",
        "nucleophile": "Morpholine",
    },
    {
        "dataset": "baumgartner",
        "init_strategy": "worst_ligand_and_more",
        "cost_aware": True,
        "n_runs": 5,
        "n_iter": 12,
        "batch_size": 5,
        "ntrain": 200,
        "prices": "update_all_when_bought",
        "surrogate": "GP",
        "acq_func": "NEI",
        "label": "Morpholine_BAUM_COST_GP_NEI",
        "cost_mod": "minus",
        "nucleophile": "Morpholine",
    },
    {
        "dataset": "baumgartner",
        "init_strategy": "worst_ligand_and_more",
        "cost_aware": False,
        "n_runs": 5,
        "n_iter": 16,
        "batch_size": 5,
        "ntrain": 200,
        "prices": "update_all_when_bought",
        "surrogate": "GP",
        "acq_func": "NEI",
        "label": "Phenethylamine_BAUM_NORMAL_GP_NEI",
        "cost_mod": "minus",
        "nucleophile": "Phenethylamine",
    },
    {
        "dataset": "baumgartner",
        "init_strategy": "worst_ligand_and_more",
        "cost_aware": True,
        "n_runs": 5,
        "n_iter": 16,
        "batch_size": 5,
        "ntrain": 200,
        "prices": "update_all_when_bought",
        "surrogate": "GP",
        "acq_func": "NEI",
        "label": "Phenethylamine_BAUM_COST_GP_NEI",
        "cost_mod": "minus",
        "nucleophile": "Phenethylamine",
    },
    {
        "dataset": "baumgartner",
        "init_strategy": "worst_ligand_and_more",
        "cost_aware": False,
        "n_runs": 5,
        "n_iter": 15,
        "batch_size": 5,
        "ntrain": 200,
        "prices": "update_all_when_bought",
        "surrogate": "GP",
        "acq_func": "NEI",
        "label": "Benzamide_BAUM_NORMAL_GP_NEI",
        "cost_mod": "minus",
        "nucleophile": "Benzamide",
    },
    {
        "dataset": "baumgartner",
        "init_strategy": "worst_ligand_and_more",
        "cost_aware": True,
        "n_runs": 5,
        "n_iter": 15,
        "batch_size": 5,
        "ntrain": 200,
        "prices": "update_all_when_bought",
        "surrogate": "GP",
        "acq_func": "NEI",
        "label": "Benzamide_BAUM_COST_GP_NEI",
        "cost_mod": "minus",
        "nucleophile": "Benzamide",
    },
]
