benchmark=[
    {"dataset":"ebdo_direct_arylation",
    "init_strategy":"worst_ligand",
    "cost_aware":True,
    "n_runs":10,
    "n_iter":20,
    "batch_size":5,
    "max_batch_cost":0,
    "ntrain":200,
    "prices":"update_when_used"
    }
    ]