benchmark=[
    {"dataset":"ebdo_direct_arylation",
        "init_strategy":"half",
        "cost_aware":False,
        "n_runs":10,
        "n_iter":20,
        "batch_size":5,
        "max_batch_cost":5,
        "ntrain":200,
    }
    ]