benchmark = [
    {
        "dataset": "buchwald",
        "init_strategy": "values",
        "cost_aware": True,
        "n_runs": 10,
        "n_iter": 20,
        "batch_size": 5,
        "max_batch_cost": 0,
        "ntrain": 200,
    },
    {
        "dataset": "buchwald",
        "init_strategy": "values",
        "cost_aware": True,
        "n_runs": 10,
        "n_iter": 20,
        "batch_size": 5,
        "max_batch_cost": 1,
        "ntrain": 200,
    },
    {
        "dataset": "buchwald",
        "init_strategy": "values",
        "cost_aware": True,
        "n_runs": 10,
        "n_iter": 20,
        "batch_size": 5,
        "max_batch_cost": 2,
        "ntrain": 200,
    },
    {
        "dataset": "buchwald",
        "init_strategy": "values",
        "cost_aware": True,
        "n_runs": 10,
        "n_iter": 20,
        "batch_size": 5,
        "max_batch_cost": 3,
        "ntrain": 200,
    },
    {
        "dataset": "buchwald",
        "init_strategy": "values",
        "cost_aware": True,
        "n_runs": 10,
        "n_iter": 20,
        "batch_size": 5,
        "max_batch_cost": 4,
        "ntrain": 200,
    },
    {
        "dataset": "buchwald",
        "init_strategy": "values",
        "cost_aware": False,
        "n_runs": 10,
        "n_iter": 20,
        "batch_size": 5,
        "max_batch_cost": 5,
        "ntrain": 200,
    },
    {
        "dataset": "ebdo_direct_arylation",
        "init_strategy": "values",
        "cost_aware": True,
        "n_runs": 10,
        "n_iter": 20,
        "batch_size": 5,
        "max_batch_cost": 0,
        "ntrain": 200,
    },
    {
        "dataset": "ebdo_direct_arylation",
        "init_strategy": "values",
        "cost_aware": True,
        "n_runs": 10,
        "n_iter": 20,
        "batch_size": 5,
        "max_batch_cost": 1,
        "ntrain": 200,
    },
    {
        "dataset": "ebdo_direct_arylation",
        "init_strategy": "values",
        "cost_aware": True,
        "n_runs": 10,
        "n_iter": 20,
        "batch_size": 5,
        "max_batch_cost": 2,
        "ntrain": 200,
    },
    {
        "dataset": "ebdo_direct_arylation",
        "init_strategy": "values",
        "cost_aware": True,
        "n_runs": 10,
        "n_iter": 20,
        "batch_size": 5,
        "max_batch_cost": 3,
        "ntrain": 200,
    },
    {
        "dataset": "ebdo_direct_arylation",
        "init_strategy": "values",
        "cost_aware": True,
        "n_runs": 10,
        "n_iter": 20,
        "batch_size": 5,
        "max_batch_cost": 4,
        "ntrain": 200,
    },
    {
        "dataset": "ebdo_direct_arylation",
        "init_strategy": "values",
        "cost_aware": False,
        "n_runs": 10,
        "n_iter": 20,
        "batch_size": 5,
        "max_batch_cost": 5,
        "ntrain": 200,
    },
    {
        "dataset": "BMS",
        "init_strategy": "values",
        "cost_aware": True,
        "n_runs": 10,
        "n_iter": 20,
        "batch_size": 5,
        "max_batch_cost": 0,
        "ntrain": 200,
    },
    {
        "dataset": "BMS",
        "init_strategy": "values",
        "cost_aware": True,
        "n_runs": 10,
        "n_iter": 20,
        "batch_size": 5,
        "max_batch_cost": 1,
        "ntrain": 200,
    },
    {
        "dataset": "BMS",
        "init_strategy": "values",
        "cost_aware": True,
        "n_runs": 10,
        "n_iter": 20,
        "batch_size": 5,
        "max_batch_cost": 2,
        "ntrain": 200,
    },
    {
        "dataset": "BMS",
        "init_strategy": "values",
        "cost_aware": True,
        "n_runs": 10,
        "n_iter": 20,
        "batch_size": 5,
        "max_batch_cost": 3,
        "ntrain": 200,
    },
    {
        "dataset": "BMS",
        "init_strategy": "values",
        "cost_aware": True,
        "n_runs": 10,
        "n_iter": 20,
        "batch_size": 5,
        "max_batch_cost": 4,
        "ntrain": 200,
    },
    {
        "dataset": "BMS",
        "init_strategy": "values",
        "cost_aware": False,
        "n_runs": 10,
        "n_iter": 20,
        "batch_size": 5,
        "max_batch_cost": 5,
        "ntrain": 200,
    },
]
