benchmark = [
    {
        "dataset": "BMS",
        "init_strategy": "random",
        "cost_aware": False,
        "n_runs": 5,
        "n_iter": 15,
        "batch_size": 5,
        "max_batch_cost": 0,
        "ntrain": 50,
    },
    {
        "dataset": "BMS",
        "init_strategy": "random",
        "cost_aware": False,
        "n_runs": 5,
        "n_iter": 15,
        "batch_size": 5,
        "max_batch_cost": 0,
        "ntrain": 100,
    },
    {
        "dataset": "BMS",
        "init_strategy": "random",
        "cost_aware": False,
        "n_runs": 5,
        "n_iter": 15,
        "batch_size": 5,
        "max_batch_cost": 0,
        "ntrain": 150,
    },
    {
        "dataset": "BMS",
        "init_strategy": "random",
        "cost_aware": False,
        "n_runs": 5,
        "n_iter": 15,
        "batch_size": 5,
        "max_batch_cost": 0,
        "ntrain": 200,
    },
    {
        "dataset": "BMS",
        "init_strategy": "random",
        "cost_aware": False,
        "n_runs": 5,
        "n_iter": 15,
        "batch_size": 5,
        "max_batch_cost": 0,
        "ntrain": 500,
    },
    {
        "dataset": "BMS",
        "init_strategy": "random",
        "cost_aware": False,
        "n_runs": 5,
        "n_iter": 15,
        "batch_size": 5,
        "max_batch_cost": 0,
        "ntrain": 1000,
    },
]
